//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.17929
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConsumeConvertWS.convertWS {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://tempuri.org/&#8221", ConfigurationName="convertWS.ConvertWSSoap")]
    public interface ConvertWSSoap {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/&#8221/VND2USD", ReplyAction="*")]
        double VND2USD(double dong);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/&#8221/VND2EUR", ReplyAction="*")]
        double VND2EUR(double dong);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/&#8221/USD2VND", ReplyAction="*")]
        double USD2VND(double usd);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/&#8221/EUR2VND", ReplyAction="*")]
        double EUR2VND(double eur);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ConvertWSSoapChannel : ConsumeConvertWS.convertWS.ConvertWSSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ConvertWSSoapClient : System.ServiceModel.ClientBase<ConsumeConvertWS.convertWS.ConvertWSSoap>, ConsumeConvertWS.convertWS.ConvertWSSoap {
        
        public ConvertWSSoapClient() {
        }
        
        public ConvertWSSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ConvertWSSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ConvertWSSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ConvertWSSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public double VND2USD(double dong) {
            return base.Channel.VND2USD(dong);
        }
        
        public double VND2EUR(double dong) {
            return base.Channel.VND2EUR(dong);
        }
        
        public double USD2VND(double usd) {
            return base.Channel.USD2VND(usd);
        }
        
        public double EUR2VND(double eur) {
            return base.Channel.EUR2VND(eur);
        }
    }
}
